### ISSUE TITLE
DSD object structure

### ISSUE THREAD

**Issue by nguy** [josephhardinee/PyDisdrometer#15]
I thought I'd bring this offline conversation into issues to record for future changes and so we know why we chose a certain design.

Currently ```DropSizeDisdrometer``` objects store data in the class (e.g. dsd.time). I propose the use of dictionaries to store the data, and specifically ```dsd.fields```. By also storing the data as dictionaries, this would allow metadata to be stored as well (especially since there is not a standard units used in the field of study). In addition, the derived fields could be stored under ```dsd.derived_fields```, which would clearly separate which fields were derived from PyDisdrometer.

Secondly, I would suggest standardizing time units within the package. I convert all time units to Epoch time in [this package](https://github.com/nguy/AWOT) for easier plotting routines.

**Comment by josephhardinee** [comment]
Sorry derived fields are currently stored in .fields. I'd be totally okay with moving all of the other data(Nd, etc) into that dictionary as well, instead of keeping them separate.

I agree with normalizing time to a standard format. The only issue I ran into before is some of the files only contained a relative time(seconds since start for instance), but no global time. In this case, I suppose we could have some kind of a default

**Comment by josephhardinee** [comment]
For the fields issue, do you want to make the changes? If not I can.

**Comment by josephhardinee** [comment]
Actually I think I can move them in without having to step on the work you're doing with the new reader.

**Comment by nguy** [comment]
Sounds good. I am mostly there on the readers I think. How about I submit that via PR and then we can tweak to make sure you like the structure? That way we don't have competing dictionary defs.

**Comment by nguy** [comment]
For time, as long as you can calculate a time, we should be able to normalize a time format. I had to do this same thing with aircraft files.

**Comment by josephhardinee** [comment]
This should be covered by PR #27 .
